### PR TITLE
fix(vehicle): fix speedometer

### LINKED ISSUE #76: [Bug]: glitch while in vehicle
### Describe the bug

sometimes this happens while in a car either on a mission or on phone 

Image
and sometimes it happens with player list 

Image

### Steps To Reproduce

open phone or view the player list while in the car

### Expected Behavior

it should not be there

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Anticheat bypass mode

Without FSL

### Additional context

_No response_

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenuV2

### PR DESCRIPTION
**Pull request by Mr-X-GTA**
Fixes https://github.com/YimMenu/YimMenuV2/issues/76

### CODE REVIEW

File: src/game/features/vehicle/Speedometer.cpp [hunk 1]
```diff
@@ -49,7 +47,7 @@ namespace YimMenu::Features
 			GRAPHICS::END_TEXT_COMMAND_SCALEFORM_STRING();
 			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
 			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(m_ScaleformHandle, "SET_METER_VALUE");
-			GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_FLOAT(veh.GetSpeed() / veh.GetMaxSpeed());
+			GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_FLOAT(veh.GetRevRatio());
```
Comment (maybegreat48) [inline src/game/features/vehicle/Speedometer.cpp]: This was intentionally not set to rev ratio because it's being reused as an actual speedometer
